id: DFC13798C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:45:08+00:00'
last_modified: '2022-05-26T11:41:32.956602+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '2000':
      image_group_id: I1PD95872
      title: དབང་གི་རིམ་པ་བསྟན་པ།
      total_pages: 1953
      order: 27
      base_file: 2000.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
