id: 556cf07093f54ad0b3e0181c80a26eab
initial_creation_type: ocr
source_metadata:
  volumes:
    8c163e03937042ba91511eef0ed0fa2f:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: ''
      total_pages: 1953
      volume_number: 27
